
# resume information
resume-index = 31226
seed = 3115114063013929202
rate = 10000     
shard = 1/1
nocapture = servername

output-filename = /tmp/masscan_output.json
output-format = json

adapter-ip = 192.168.68.118
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 1-65535
range = 10.130.156.175

